### ISSUE TITLE
Random access to archive entry (zip)

### ISSUE THREAD

**Issue by katyukha** [rtbo/squiz-box#18]
Is it possible (or will it be possible in future) to read random entry from archive without need to unpack all its content?

For example, if zip-archive contains `manifest.json` and i want to read only this file to decide if i need to unpack archive or not.

Thanks)

**Comment by rtbo** [comment]
Hi, the ZIP unbox algorithm will only uncompress data if you call `UnboxEntry.byChunk` (`byChunk` is also called by `extractTo`). No decompression resources is allocated at all if you don't.
So you can easily filter-out the files you don't need, Squiz-Box will only uncompress `manifest.json`.

Now in regards to true random access, it is not possible at the moment but might be in the future.
To explain further, the ZIP format has two file info databases, one file info entry before each compressed stream, and one at the end of the ZIP file.
So you if you unpack ZIP from e.g. a network stream, Squiz-Box will read the file info entry before each compressed stream, and skip the bytes you don't read. The whole stream is processed in a single pass.

If you unpack ZIP from a `std.stdio.File`, Squiz-Box will read the database at the end all at once, and use it.
This boosts the performances and allows to save the `UnboxEntry` list in memory and use them in random order.
But you will still scan each entry in the order they are declared in the file.
I'd need to make some dedicated API for random access in addition to the range API to use the central database in a random access way.

Here an example of the two possibilities:
```d
import squiz_box;
import std.net.curl : byChunk;
import std.stdio : File;

const url = "https://web.site/zipfile.zip";
byChunk(url)
    .unboxZip()
    .filter!(e => e.path == "manifest.json") 
    .takeOne()
    .each!(e => e.extractTo("somedir"));

const path = "zipfile.zip";
File(path)
    .unboxZip()
    .filter!(e => e.path == "manifest.json")
    .takeOne()
    .each!(e => e.extractTo("somedir"));
```

**Comment by katyukha** [comment]
Hi,

Thanks for inforamtion. I will check it.
